# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# ROOST_METHOD_HASH=d4875ba7c9
# ROOST_METHOD_SIG_HASH=deac2363dc
# 
#  ########## Scenario ########## 
# 
# {
#   feature: 'Feature: Credential Wallet API\r\n' +
#     '  As a user of the Credential Wallet API\r\n' +
#     '  I want to get registration details of people allowed to receive credentials \r\n' +
#     '  So that I can manage my account effectively',
#   background: 'Background:\r\n    Given the base URL is "http://localhost:8080"',
#   rule: null,
#   scenario: {
#     title: 'Scenario: Get Registration Details Of Recipient Person',
#     steps: 'Given id of recipient as 27364922937 in path parameter\r\n' +
#       'And size=13 and offset=42 in request query\r\n' +
#       'When the client sends a GET request to endpoint "/recipients/persons/{id}/registrations" \r\n' +
#       'When authentication token is sent in request\r\n' +
#       'Then for successful request having status code 200, Verify that headers have api-version, page-size and  page-offset\r\n' +
#       'And response body must have element registrations and total.',
#     examples: ''
#   }
# }
# 

# ********RoostGPT********
Feature: Credential Wallet API
  As a user of the Credential Wallet API
  I want to get registration details of people allowed to receive credentials
  So that I can manage my account effectively

  Background:
    * url 'http://localhost:8080'
    * def CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL = karate.properties['CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL'] || karate.get('CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL', 'http://localhost:4010')
    * def CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_AUTH_TOKEN = karate.properties['CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_AUTH_TOKEN'] || karate.get('CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_AUTH_TOKEN', 'Bearer_Dummy_Token')

  Scenario: Get Registration Details Of Recipient Person
    * url CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_URL
    And path '/recipients/persons/27364922937/registrations'
    And param size = 13
    And param offset = 42
    And header Authorization = CREDENTIALREGISTER_WALLET_1_0_0_RESOLVED_88376FEFA0_AUTH_TOKEN
    When method get
    Then status 200
    And match responseHeaders['api-version'][0] == '1.0.0'
    And match responseHeaders['page-size'][0] == 13
    And match responseHeaders['page-offset'][0] == 42
    And match response.registrations != null
    And match response.total != null
