# ********RoostGPT********

# Test generated by RoostGPT for test new-karate-test using AI Type  and AI Model 
# 
# Feature file generated for /accounts_post for http method type POST 
# RoostTestHash=53e96f9805
# 
# 

# ********RoostGPT********
Feature: Account Creation

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = { 'auth-token': '#(authToken)' }

  Scenario Outline: Successful creation of a new account
    Given path '/accounts'
    And request { 'email': '<email>' }
    And headers headers
    When method post
    Then status 201
    And match responseHeaders['api-version'] == '#string'
    And match responseHeaders['auth-token'] == '#string'

    Examples:
      | read('accounts_post.csv') |

  Scenario Outline: Unsuccessful creation of a new account with invalid email
    Given path '/accounts'
    And request { 'email': '<email>' }
    And headers headers
    When method post
    Then status 400
    And match responseHeaders['api-version'] == '#string'
    And match response.error == '#string'
    And match response.description == '#string'

    Examples:
      | email          |
      | 'invalidEmail' |
      | 'test@invalid' |
