# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_post for http method type POST 
# RoostTestHash=c0bc5294a0
# 
# 

# ********RoostGPT********
Feature: Test the Update Pet Endpoint

  Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase
    * configure headers = { "Authorization": "#(karate.properties['petstore_auth'])" }

  Scenario Outline: Verify updating a pet's details with valid inputs
    Given path 'v2/pet/<petId>'
    And request """ 
    { 
      "name": "<name>", 
      "status": "<status>" 
    } 
    """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.id == '#number'
    And match response.name == '#string'
    And match response.status == '#string'
    And match response.category == '#object'
    And match response.category.id == '#number'
    And match response.category.name == '#string'
    And match response.tags == '#[] #array'
    And match response.tags[*].id == '#number'
    And match response.tags[*].name == '#string'

    Examples:
      | petId | name    | status      |
      | 101   | Max     | available   |
      | 102   | Buddy   | sold        |

  Scenario: Verify updating pet details with invalid inputs
    Given path 'v2/pet/abc'
    And request """ 
    { 
      "name": "", 
      "status": "" 
    } 
    """
    When method POST
    Then status 405
