# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=561990ad39
# 
# 

# ********RoostGPT********
Feature: Test scenarios for the /v2/pet/{petId} endpoint

  Background:
    * def urlBase = karate.properties['PETSTORE_API_HOST']
    * url urlBase
    * configure headers = """ 
    { 
      api_key: #(karate.properties['AUTH_TOKEN']) 
    }
    """

  Scenario Outline: Get pet by ID with successful response
    Given path 'v2/pet/<petId>'
    When method GET
    Then status 200
    And match response == '''#object'''
    And match response.id == '''#number'''
    And match response.category == '''#object'''
    And match response.category.id == '''#number'''
    And match response.category.name == '''#string'''
    And match response.name == '''#string'''
    And match response.photoUrls == '''#array'''
    And match each response.photoUrls == '''#string'''
    And match response.tags == '''#array'''
    And match each response.tags == '''#object'''
    And match each response.tags.id == '''#number'''
    And match each response.tags.name == '''#string'''
    And match response.status == '''#string'''
    And match response.status in ['available', 'pending', 'sold']

    Examples:
      | petId |
      |     1 |
      |   999 |
      | 12345 |

  Scenario: Get pet by ID with invalid ID supplied
    Given path 'v2/pet/abc'
    When method GET
    Then status 400

  Scenario Outline: Get pet by ID with pet not found
    Given path 'v2/pet/<petId>'
    When method GET
    Then status 404

    Examples:
      | petId  |
      | 999999 |
      | 123456 |
      | 789012 |
