# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Claude AI and AI Model claude-3-5-haiku-20241022
# 
# Feature file generated for /store/inventory_get for http method type GET 
# RoostTestHash=a66f7079af
# 
# 

# ********RoostGPT********
Feature: Store Inventory API

  Background:
    * def urlBase = karate.properties['demoapp_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['demoapp_AUTH_TOKEN']
    * configure headers = { 'api_key': '#(authToken)' }

  Scenario: Get Store Inventory Successfully
    Given path '/v2/store/inventory'
    When method GET
    Then status 200
    And match response == '#object'
    And match response contains only '#[] #number'
    And match response == '#each { key: "#number" }'
    And def responseKeys = karate.keys(response)
    And assert responseKeys.length > 0
    And if (responseKeys.includes('approved'))
    * assert response.approved >= 0
    And if (responseKeys.includes('pending'))
    * assert response.pending >= 0
