# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Claude AI and AI Model claude-3-5-haiku-20241022
# 
# Feature file generated for /store/inventory_get for http method type GET 
# RoostTestHash=a66f7079af
# 
# 

# ********RoostGPT********
Feature: Store Inventory API

Background:
  * def urlBase = karate.properties['demoapp_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
  * url urlBase
  * def authToken = karate.properties['demoapp_AUTH_TOKEN']
  * configure headers = { 'api_key': authToken }

Scenario: Get Pet Inventory by Status
  Given path '/v2/store/inventory'
  When method GET
  Then status 200
  And match response == '#object'
  And match response contains deep '#[] #number'
  
  And match response.each(function(value){ 
    return typeof value === 'number' 
  })
  
  * def inventoryStatuses = karate.keys(response)
  And match inventoryStatuses == '#notnull'
  
  And match response.each(function(value){ 
    return Number.isInteger(value) && value >= 0 
  })
