# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=999efa10b6
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Cancel Product Order Create Event By Client
    * request
      """
      {
          "notification": {
              "date": "<date>",
              "customer": {
                  "subscriberId": "<subscriberId>"
              },
              "order": {
                  "id": "<id>",
                  "correlationOrder": "<correlationOrder>",
                  "associatedDocument": "<associatedDocument>",
                  "issue": {
                      "code": "<code>",
                      "description": "<description>",
                      "type": "<type>",
                      "observation": "<observation>",
                      "updateDate": "<updateDate>",
                      "action": "<action>",
                      "task": "<task>",
                      "fieldActivity": "<fieldActivity>",
                      "reason": "<reason>"
                  },
                  "type": "<type>",
                  "code": "<code>",
                  "description": "<description>",
                  "lostEquipment": "<lostEquipment>",
                  "resource": {
                      "gponAccess": "<gponAccess>",
                      "devices": {
                          "device": [
                              {
                                  "category": "<category>",
                                  "type": "<type>",
                                  "description": "<description>",
                                  "state": "<state>",
                                  "usageState": "<usageState>",
                                  "startOperatingDate": "<startOperatingDate>",
                                  "resourceCharacteristic": [
                                      {
                                          "name": "<name>",
                                          "value": "<value>"
                                      }
                                  ]
                              }
                          ]
                      }
                  }
              }
          }
      }
      """
    * method post
    * path '/listener/cancelProductOrderCreateEvent'
    * header Authorization = #(karate.properties['AUTH_TOKEN'])
    * header Content-Type = 'application/json'
    * header Accept = 'application/json'
    * header responsePath = '/listener/cancelProductOrderCreateEvent'
    * status 204
    * match $ == '#(true)'
    * match responseHeaders['Content-Type'] CONTAINS 'application/json'
    * match responseHeaders['responsePath'] == '/listener/cancelProductOrderCreateEvent'

    Examples:
      | read('listener_cancelProductOrderCreateEvent_post.csv') |

  Scenario: Cancel Product Order Create Event By Client with invalid input
    * request
      """
      {
          "notification": {
              "date": "invalid_date",
              "customer": {
                  "subscriberId": ""
              },
              "order": {
                  "id": "",
                  "correlationOrder": "",
                  "associatedDocument": "",
                  "issue": {
                      "code": "",
                      "description": "",
                      "type": "",
                      "observation": "",
                      "updateDate": "",
                      "action": "",
                      "task": "",
                      "fieldActivity": "",
                      "reason": ""
                  },
                  "type": "",
                  "code": "",
                  "description": "",
                  "lostEquipment": "",
                  "resource": {
                      "gponAccess": "",
                      "devices": {
                          "device": [
                              {
                                  "category": "",
                                  "type": "",
                                  "description": "",
                                  "state": "",
                                  "usageState": "",
                                  "startOperatingDate": "",
                                  "resourceCharacteristic": [
                                      {
                                          "name": "",
                                          "value": ""
                                      }
                                  ]
                              }
                          ]
                      }
                  }
              }
          }
      }
      """
    * method post
    * path '/listener/cancelProductOrderCreateEvent'
    * header Authorization = #(karate.properties['AUTH_TOKEN'])
    * header Content-Type = 'application/json'
    * header Accept = 'application/json'
    * header responsePath = '/listener/cancelProductOrderCreateEvent'
    * status 400
    * match $ == '#(true)'
    * match responseHeaders['Content-Type'] CONTAINS 'application/json'
    * match responseHeaders['responsePath'] == '/listener/cancelProductOrderCreateEvent'
