# ********RoostGPT********

# Test generated by RoostGPT for test test-karate-with-BR using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=99e96e3191
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test Product Order Information Required Event - Scenario <scenario>
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      <requestBody>
      """
    When method post
    Then status <expectedStatus>

    Examples:
      | scenario | requestBody                 | expectedStatus |
      |        1 | <notifRequest>              |            204 |
      |        2 | <invalidRequest>            |            400 |
      |        3 | <authFailedRequest>         |            401 |
      |        4 | <serverErrorRequest>        |            500 |
      |        5 | <serviceUnavailableRequest> |            503 |
      |        6 | <timeoutRequest>            |            504 |

  Scenario: Define Request Bodies
    * def notifRequest =
      """
      {
        "notification": {
          "date": "2023-03-15T13:45:30.123Z",
          "customer": {
            "subscriberId": "123456789012345678901234567890"
          },
          "order": {
            "id": "20230315000001",
            "correlationOrder": "10",
            "associatedDocument": "VTT001",
            "issue": {
              "code": "7029",
              "description": "Pendencia de agendamento",
              "type": "CLIENTE",
              "observation": "",
              "updateDate": "2021-02-17T17:19:50-03:00",
              "action": "abrir",
              "task": "",
              "fieldActivity": "true",
              "reason": "PROJETO"
            }
          },
          "type": "PROCESS",
          "code": "1",
          "description": "Enviando Atualização de Ordem",
          "lostEquipment": "true",
          "resource": {
            "gponAccess": "GPON001",
            "devices": {
              "device": [
                {
                  "category": "CAT1",
                  "type": "DEVICE_TYPE1",
                  "description": "Device Description",
                  "state": "ACTIVE",
                  "usageState": "IN_USE",
                  "startOperatingDate": "2021-02-17T17:19:50-03:00",
                  "resourceCharacteristic": [
                    {
                      "name": "item1",
                      "value": "value1"
                    }
                  ]
                }
              ]
            },
            "fiberPath": {
              "items": {
                "item": [
                  {
                    "name": "fiberPath1",
                    "value": "value1"
                  }
                ]
              }
            }
          }
        }
      }
      """
    * def invalidRequest =
      """
      {
        "notification": {
          "date": "invalid_date"
        }
      }
      """
    * def authFailedRequest =
      """
      {
        "notification": {
          "date": "2023-03-15T13:45:30.123Z"
        }
      }
      """
    * def serverErrorRequest =
      """
      {
        "notification": {
          "date": "2023-03-15T13:45:30.123Z"
        }
      }
      """
    * def serviceUnavailableRequest =
      """
      {
        "notification": {
          "date": "2023-03-15T13:45:30.123Z"
        }
      }
      """
    * def timeoutRequest =
      """
      {
        "notification": {
          "date": "2023-03-15T13:45:30.123Z"
        }
      }
      """
