# ********RoostGPT********

# Test generated by RoostGPT for test karate-new-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /store/order_post for http method type POST 
# RoostTestHash=340dd2a1e1
# 
# 

# ********RoostGPT********
Feature: Place an order for a pet

  Background:
    * def urlBase = karate.properties['URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Place a new order for a pet
    Given path '/v2/store/order'
    And request
      """
      {
        "id": <id>,
        "petId": <petId>,
        "quantity": <quantity>,
        "shipDate": "<shipDate>",
        "status": "<status>",
        "complete": <complete>
      }
      """
    When method POST
    Then status <statusCode>
    And match response contains
      """
      {
        "id": #number,
        "petId": #number,
        "quantity": #number,
        "shipDate": "#string",
        "status": "<status>",
        "complete": #boolean
      }
      """

    Examples:
      | id | petId | quantity | shipDate               | status      | complete | statusCode |
      |  1 |   101 |        1 | "2023-10-21T13:30:00Z" | "placed"    | true     |        200 |
      |  2 |   102 |        2 | "2023-10-22T13:30:00Z" | "approved"  | false    |        200 |
      |  3 |   103 |        0 | "2023-10-23T13:30:00Z" | "delivered" | true     |        200 |
      |  4 |   104 |        3 | ""                     | "placed"    | true     |        400 |

  Scenario Outline: Invalid Order
    Given path '/v2/store/order'
    And request
      """
      {
        "id": <id>,
        "petId": <petId>,
        "quantity": <quantity>,
        "shipDate": "<shipDate>",
        "status": "<status>",
        "complete": <complete>
      }
      """
    When method POST
    Then status <statusCode>

    Examples:
      | id | petId | quantity | shipDate               | status   | complete | statusCode |
      |  5 |   105 |       -1 | "2023-10-24T13:30:00Z" | "placed" | true     |        400 |
