# ********RoostGPT********

# Test generated by RoostGPT for test karate-new-test using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /store/order_post for http method type POST 
# RoostTestHash=340dd2a1e1
# 
# 

# ********RoostGPT********
Feature: Store Order API

  Background:
    * def urlBase = karate.properties['URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Place an order for a pet
    Given path '/v2/store/order'
    And request
      """
      {
        "id": <id>,
        "petId": <petId>,
        "quantity": <quantity>,
        "shipDate": '<shipDate>',
        "status": '<status>',
        "complete": <complete>
      }
      """
    And header api_key = '{{$processEnvironment.AUTH_TOKEN}}'
    When method POST
    Then status <statusCode>
    And match response ==
      """
      {
        "id": '#number',
        "petId": '#number',
        "quantity": '#number',
        "shipDate": '#string',
        "status": '#string',
        "complete": '#boolean'
      }
      """
    And match response.id == <id>
    And match response.petId == <petId>
    And match response.quantity == <quantity>
    And match response.shipDate == '$[0000-00-00T00:00:00.000Z]'
    And match response.status in ['placed', 'approved', 'delivered']
    And match response.complete == <complete>

    Examples:
      | id | petId | quantity | shipDate                 | status    | complete | statusCode |
      |  1 |    10 |        1 | 2023-07-14T12:00:00.000Z | placed    | true     |        200 |
      |  2 |    20 |        2 | 2023-07-15T12:00:00.000Z | approved  | false    |        200 |
      |  3 |    30 |        3 | 2023-07-16T12:00:00.000Z | delivered | true     |        200 |
      |  4 |    40 |        4 | 2023-07-17T12:00:00.000Z | placed    | true     |        400 |

  Scenario: Place an order for a pet with missing required fields
    Given path '/v2/store/order'
    And request
      """
      {
        "petId": 50,
        "quantity": 5,
        "shipDate": '2023-07-18T12:00:00.000Z',
        "status": 'placed',
        "complete": true
      }
      """
    And header api_key = '{{$processEnvironment.AUTH_TOKEN}}'
    When method POST
    Then status 400

  Scenario: Place an order for a pet with invalid status
    Given path '/v2/store/order'
    And request
      """
      {
        "id": 6,
        "petId": 60,
        "quantity": 6,
        "shipDate": '2023-07-19T12:00:00.000Z',
        "status": 'invalid',
        "complete": true
      }
      """
    And header api_key = '{{$processEnvironment.AUTH_TOKEN}}'
    When method POST
    Then status 400
