/*
Test generated by RoostGPT for test MiniProjects using AI Type Vertex AI and AI Model code-bison-32k

{
  background: 'Given the base URL is "http://localhost:8080"',
  rule: null,
  scenario: 'Get all products\r\n' +
    '        When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '        Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
 package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class getAllProductsTest {

    @Test
    public void getAllProducts() {
        // Given the base URL is "http://localhost:8080"
        RestAssured.baseURI = System.getenv("API_HOST");

        // When the client sends a GET request "/api/products" to get the list of all products
        given()
                .contentType(ContentType.JSON)
                .when()
                .get("/api/products")

                // Then the list of products returned should be empty
                .then()
                .statusCode(200)
                .body("size()", equalTo(0));
    }
}