// ********RoostGPT********
/*
Test generated by RoostGPT for test ProductOrdering-restAssured-API-Spec-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated for /productOrder/{order.Id}_patch for http method type PATCH in rest-assured framework

RoostTestHash=baabcd7d73


*/

// ********RoostGPT********

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.19.1</version>
            <configuration>
                <includes>
                    <include>**/*ProductOrderOrderIdPatch*.java</include>
                </includes>
            </configuration>
        </plugin>
    </plugins>
</build>
