# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /availabilityCheck_post for http method type POST 
# RoostTestHash=a251be39a4
# 
# 

# ********RoostGPT********
Feature: Availability check

  Background:
    * def urlBase = karate.properties['url1_tresourcePoolManagement_(2)_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: '#(karate.properties['url1_tresourcePoolManagement_(2)_AUTH_TOKEN'])' }
