# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /availabilityCheck_post for http method type POST 
# RoostTestHash=2445a4c161
# 
# 

# ********RoostGPT********
Feature: Check availability based on the given endpoint

  Background:
    * def urlBase = karate.properties['abcd_URL1_TRESOURCEPOOLMANAGEMENT__2__URL1_TRESOURCEPOOLMANAGEMENT__2__URL1_TRESOURCEPOOLMANAGEMENT__2__URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')

  Scenario Outline: Test Post availability check
    Given url urlBase
    And path '/availabilityCheck'
    And request <Data>
    When method post
    Then status <StatusCode>
    And match $ == <ResponseBody>

    Examples:
      | Data                                                                                                                               | StatusCode | ResponseBody                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | '''{"customer":{"subscriberId":"SVTL001"},"address":{"id":14393,"complement":{"complements":[{"type":"ES","value":"ARC201"}]}}}''' |        200 | '''{"control": {"type":"S", "code":"200", "message":"OK"}, "resource": {"inventoryId":1766156, "maxBandwidth":1000, "availabilityType":1, "availabilityCode":0, "availabilityDescription":"Viável - Viabilidade técnica confirmada", "products": {"product": [{"type":"Banda Larga", "catalogId":"BL_100MB", "name":"VELOC_100MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_200MB", "name":"VELOC_200MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_400MB", "name":"VELOC_400MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_500MB", "name":"VELOC_500MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_1000MB", "name":"VELOC_1000MBPS", "technology":"", "best_offer": true}]}}}''' |
      | '''{"customer":{"subscriberId":"SVTL001"},"address":{"id":2449}}'''                                                                |        200 | '''{"control": {"type":"S", "code":"200", "message":"OK"}, "resource": {"inventoryId":261313, "maxBandwidth":400, "availabilityType":3, "availabilityCode":144, "availabilityDescription":"Viável com obra - CDO(s) sem porta livre e em célula disponível", "products": {"product": [{"type":"Banda Larga", "catalogId":"BL_100MB", "name":"VELOC_100MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_200MB", "name":"VELOC_200MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_400MB", "name":"VELOC_400MBPS", "technology":"", "best_offer": true}]}}}'''                                                                                                                                                             |
      | '''{"customer":{"subscriberId":"SVTL001"},"address":{"id":2449,"complement":{"complements":[{"type":"ES","value":"ARC201"}]}}}'''  |        200 | '''{"control": {"type":"S", "code":"200", "message":"OK"}, "resource": {"inventoryId":261313, "maxBandwidth":300, "availabilityType":3, "availabilityCode":144, "availabilityDescription":"Viável com obra - CDO(s) sem porta livre e em célula disponível", "products": {"product": [{"type":"Banda Larga", "catalogId":"BL_100MB", "name":"VELOC_100MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_200MB", "name":"VELOC_200MBPS", "technology":""}, {"type":"Banda Larga", "catalogId":"BL_300MB", "name":"VELOC_300MBPS", "technology":"", "best_offer": true}]}}}'''                                                                                                                                                             |
